<?php
/**
 * Created by PhpStorm.
 * User: letuananh
 * Date: 2/16/17
 * Time: 17:53:52
 */

namespace DynamicFormManager\Fields;


use DynamicFormManager\Widgets\CheckboxSelectMultiple;

class MultipleSelectField extends Field
{
    public $widget = CheckboxSelectMultiple::class;

    public function __construct($options)
    {
        $this->defaultOption['choices'] = [];
        $options = array_merge($this->defaultOption, $options);
        parent::__construct($options);

        $this->widget->choices = $options['choices'];
        $this->widget->wrap_label= $options['wrap_label'];
    }

    public function clean($value)
    {
        if(is_null($value))
            return [];
        return parent::clean($value); // TODO: Change the autogenerated stub
    }


}